---
notifications:
  email:
    - slyphon@gmail.com

# pull in releaseops submodule
before_install:
  - git submodule update --init --recursive

env:
  - SPAWN_ZOOKEEPER='true'

rvm:
  - 1.9.3
  - 1.9.2
  - 1.8.7
  - ree
  - jruby-18mode
  - jruby-19mode

bundler_args: --without development docs coverage

# blacklist
branches:
  except:
    - dev/zookeeper-st

